### ISSUE TITLE
Add URLDecode

### ISSUE THREAD

**Issue by Pysis868** [a-bentofreire/bracketstoix#16]
This extension seems to have both HTML-Encode and -Decode, but only has URL-Encode without URL-Decode.  This is odd to not have the compliment for all of these related functions.

Request to add the URLDecode function.

**Comment by apptoix** [comment]
The functions have been added based on usage frequency according to my personal experience.
That function can be added. 
At the moment the extension is going under several changes that will be published in September, so it's preferable that I implemented since it's quicker than sync both versions.
