### ISSUE TITLE
Compiling .scss

### ISSUE THREAD

**Issue by lindsaywebstudio** [a-bentofreire/bracketstoix#23]
Hello. I installed sass via terminal, and confirmed it is correctly installed. However, nothing happens when I click to compile my .scss file using this extension. I checked the IX options for the compiler and it is set to: sass --sourcemap "{{in}}" "{{out}}" 

I have tried removing "--sourcemap" as when I use that in terminal it says it's no longer needed, but that didn't change anything. I have checked 'compile on save' and have clicked the manual Compile option from the IX menu, but no luck. Do I need to have something else installed for this to work?

I am using the most recent versions of Brackets, IX and Saas.

Thanks for your help!

**Comment by a-bentofreire** [comment]
Hi. 
In order to assist you , please, provide the following information:
- os name,
- os version
- which shell do you use.
- sass version 
- the cmdline qnd output of sass executed from the terminal.

Thank you

**Comment by lindsaywebstudio** [comment]
Hello. I just checked it in terminal to confirm my command line, where I
discovered there was an error in the scss. Sorry for wasting your time -- I
didn't realize I needed a separate scss lint in brackets to see those
errors. Once I fixed that, your extension compiled the CSS correctly.

However, now that I see the compiled css -- is there a way to turn off the
scss line commenting?

Thank you!

**Comment by a-bentofreire** [comment]
Hi,
Since you tried with different parameters, did you put back the original parameters in IX.

sass --sourcemap "{{in}}" "{{out}}"

If you open the brackets dev-tools, does it shows any error on the console?
I'm sorry, but I don't understand the issue regarding the line comments:
- where does it shows,
- and what does it says?
