### ISSUE TITLE
ReplaceIX give error "Step cant be empty"

### ISSUE THREAD

**Issue by schroef** [a-bentofreire/bracketstoix#24]
Im trying out this addon on OSX and when i try the replace function on a selected piece of text, i get an error about Step field cant be empty. When i hover over it, it states something about ctr up / down. I dont understand this error than looking at that hover info

<img width="614" alt="screen shot 2018-07-25 at 14 20 55" src="https://user-images.githubusercontent.com/6923008/43219768-3a432a04-9016-11e8-9607-a81a0d2c5f0f.png">

**Comment by schroef** [comment]
Simply adding 1 in both fields works. BUt there is no info about the usage though?

**Comment by a-bentofreire** [comment]
The new version which will be deployed until 2018-07-28 will fix this issue.
It will no longer be required to fill step field.

**Comment by schroef** [comment]
You deployed from 28-07 i think??

**Comment by a-bentofreire** [comment]
Today I already pushed the fixes to Github, I will push to brackets registry friday late night (Taipei), afternoon(Europe), morning(US)

**Comment by schroef** [comment]
ahhh okay so i could drop in the code just manually.

Nice!

**Comment by a-bentofreire** [comment]
By this time the time of your message was already on brackets registry.

**Comment by schroef** [comment]
I notice the update, yet i dont understand its still there but know its already filled with 1 in both. Yet the hover info states it should be empty??? ALso the hover info is to much to read before it fades away again.

**Comment by a-bentofreire** [comment]
The tooltip display time is controlled by chrome which is the brackets support engine.

The message is: 
- Replace: Use #{d}#, #{x}#, #{X}#, #{<value>d}#, #{0<value>d}# for numbering macro.
- Start: Leave empty for no numbering, since it slows down the process and only supports a small regular expression subset replacement. Must have Regular Expression checked

e.g.
- Find: `(\w+)`
- Replace: `#{d}#. $1`
- Start: 1
- Step: 1

Must have Regular Expression checked!!!
If Start and Step are empty it will operate as a normal regular expression

**Comment by schroef** [comment]
Sorry to bump this up again, i dont quit understand the find replace options.

I got a file which has settings and its one big string of text, each option is separated by ", " (comma + space). I now want to find all these and add a return/enter.

I tried find ", " but if dont understand how to add \n or \r for the regular expression. It keeps adding it as regular text. I tried putting it between the curly brackets, but doesnt work

**Comment by a-bentofreire** [comment]
do you have something like:  
> oranges are orange,  apples are red,  

and want to transform to:

> 1. oranges are orange,  
> 2. apples are red,  

1. IX Split, marker its `,\s*`  
2.  ReplacetoIX: `^(.*)$` with `#{d}#. $1`.  
It must have multiline and regular expression option on.
