### ISSUE TITLE
[REQ]Find replace with use of regular expression

### ISSUE THREAD

**Issue by schroef** [a-bentofreire/bracketstoix#25]
I would like to know if its possible to add Regular Expression functionality to ReplaceIX. I already saw a checkbox Regular Expression, but i guess that is for checking those as well.

Is there perhaps already a feature i didnt see.

**Comment by a-bentofreire** [comment]
ReplaceIX has Regular Expression, just make sure Start and Step are empty and Regular Expression is checked.
