### ISSUE TITLE
How to turn off the compiler?

### ISSUE THREAD

**Issue by mulihi** [a-bentofreire/bracketstoix#26]
After trying the compiler of BracketstoIX I use now the
cmdline in the terminal: sass --watch sass:css and it works fine.

Now I want to deactivate the compiler of Brackets, but I cannot. Also if I deactivate BracketstoIX it still compiles the sass files into css files.
How to turn off the compiler?

My system information:
OS name: Apple Mac
OS version: OS X El Capitan
Sass version: 1.10.2 compiled with dart2js 2.0.0-dev.69.5

I'm new to github, hopefully here is the right place to post this question...
Thanks in an advance for an answer.

**Comment by a-bentofreire** [comment]
You must have another extension that is automatically compiling, it's not BracketstoIX.
BracketstoIX doesn't compiles automatically nor executes itself it you disable the extension.

**Comment by mulihi** [comment]
Thank you. Sorry for the unawareness.
